version: '3.5'

services:
  db:
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres-todo
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp:latest
    container_name: api-todo
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env.production
    volumes:
      - ./src:/app/src
