name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.DROPLET_IP}} # Remote server address / ip - required
          user: ${{secrets.DROPLET_USERNAME}} # Remote server port -  Default: 22 - optional
          private_key: ${{secrets.SSH_KEY}} # Remote server user - required
          command: |
            cd /root/api/
            git checkout main;
            git pull;
