name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to DigitalOcean
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} scp -r ./ ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_IP }}:/root/api/
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          DROPLET_USERNAME: ${{ secrets.DROPLET_USERNAME }}
          DROPLET_IP: ${{ secrets.DROPLET_IP }}

      - name: SSH into DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_IP }} << 'EOF'
            cd /root/api/
            docker-compose down
            docker-compose up -d
            EOF
