name: Deploy to DigitalOcean Droplet
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        env:
          INPUT_COMMAND_TIMEOUT: 2
        with:
          host: ${{secrets.DROPLET_IP}}
          username: ${{secrets.DROPLET_USERNAME}}
          key: ${{secrets.SSH_KEY}}
          script: |
            docker-compose down
            docker rm -f $(docker ps -a -q)
            docker volume rm $(docker volume ls -q)
            rm -R ~/api
            git clone https://github.com/vad9ss6/todo-app-backend.git
            mv ~/todo-app-backend ~/api 
            cd ~/api/ 
            docker-compose build
            docker-compose up
