name: Deploy to DigitalOcean Droplet
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DROPLET_IP}}
          username: ${{secrets.DROPLET_USERNAME}}
          key: ${{secrets.SSH_KEY}}
          script: |
            kill -9 $(ps -ef | grep 'ngrok' | grep -v 'grep' | awk '{print $2}')
            docker-compose down
            rm -R ~/api
            git clone https://github.com/vad9ss6/todo-app-backend.git
            mv ~/todo-app-backend ~/api 
            cd ~/api/ 
            docker-compose build
            docker-compose up -d
            cd ~/
            ngrok http http://64.226.91.13:3000 > /dev/null &
            NGROK_PID=$!
            sleep 2
            PUBLIC_URL=$(curl -sS http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
            echo $PUBLIC_URL
            kill -9 $NGROK_PID
            exit 0
